version: "3"
services:
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    restart: always
    volumes:
      - .cache:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test123
